language: python
python:
  - "2.6"
  - "2.7"
install:
  #- pip install pep8 --use-mirrors
  #- pip install pyflakes --use-mirrors
  - pip install robotframework
  - pip install selenium
  - pip install decorator
  - pip install docutils
  #- "if [[ ${BROWSER} == 'ie' ]]; then pip install ie_only_pkg; fi"
#before_script:
  #- "export DISPLAY=:99.0"
  #- "sh -e /etc/init.d/xvfb start"
script:
  - "pybot /tests/google/google_test.txt"
